### ISSUE TITLE
LDAP as a backend auth

### ISSUE THREAD

**Issue by zolech** [mlowicki/rhythm#15]
Hello,

Since not everyone uses gitlab, would it be possible to add ldap/ad as a backend for authentication? Most of the companies still uses AD od LDAP as a main authentication database, that would be killer feature :)

**Comment by mlowicki** [comment]
Hi,

I knew it was coming ;-) GitLab authenticator was easiest for me to add but LDAP is definitely sth worth to support. Bootstrapping OpenLDAP should be easy with https://github.com/osixia/docker-openldap and I can work on it. Do you have any proposal how it should work exactly or configuration options to support to help with your scenario?

**Comment by mlowicki** [comment]
So I'm thinking about such parameters needed for first scenario where authorization is based on ACL defined in file:
* `addrs` (required) - list of LDAP servers with protocol so e.g. `["ldap://example.com:389", "ldaps://example.com:636"]. Servers will be tried out from first to last one till connection will be established or list will be exhausted
* `dn` - distinguished name with `{username}` placeholder like `'uid={username},dc=example,dc=com'`
* `acl`  - absolute path to ACL file which can look like:
```
{
    "john": {
        "groupX": "read-only",
        "groupX/projectY": "read-write"
    }
    "alan": {

    }
}
```

Credentials can be passed via `Authorization` HTTP header:
```
Authorization: Basic dm9yZGVsOnZvcmRlbA==
```

Please let me know what do you think.

**Comment by mlowicki** [comment]
I guess we can copy implementation used by Vault - https://github.com/hashicorp/vault/blob/master/helper/ldaputil/client.go#L101:
* if `DiscoverDN` is true then anonymous bind is used first and then search query (https://github.com/hashicorp/vault/blob/master/helper/ldaputil/client.go#L120)  to get `bind DN`
* if `DiscoverDN` is false then it works I've described in https://github.com/mlowicki/rhythm/issues/15#issuecomment-429471511 (to get `bind DN`)

Once `bind DN` is ready we can use it to call bind.

**Comment by mlowicki** [comment]
@zolech Are you saying that bind `sAMAccountName=someone,dc=example,dc=org` won't work in AD or you're saying only about case where bind was successful but retrieving data using such DN won't work?

**Comment by mlowicki** [comment]
@zolech will be done on branch https://github.com/mlowicki/rhythm/tree/ldap_authorizer. For now I've added LDAP authentication only. Next step is to do ACL based on configuration file and then by LDAP groups. If you can test authentication part using existing LDAP / AD server that would be great.

**Comment by zolech** [comment]
I am getting authentication error: `""Error": "LDAP Result Code 49 \"Invalid Credentials\": 80090308: LdapErr: DSID-0C0903A9, comment: AcceptSecurityContext error, data 52e, v1db1"`

config:

	"api": {
    		"addr": "localhost:8888",
    		"auth": {
        		"backend": "ldap",
        		"ldap": {
            			"addrs": ["ldap://dc1.example.pl"],
            			"userdn": "cn=users,dc=office,dc=example,dc=pl",
            			"userattr": "sAMAccountname"
        		}
    		}
	},

Credentials are ok, I tested them in every application that uses our AD server. Unfortunately I can't see what ldap query looks like. Some debug option for that would be helpful. I am not a programmer so modyfying code on my own would be hard.

**Comment by zolech** [comment]
Yeah I know how to set Authorization header. I've found the problem and it is related to what I wrote earlier, there is no way to bind to AD with this dn `sAMAccountname=USERNAME,cn=users,dc=office,dc=example,dc=pl`. I am forced to use CN: `CN=USERNAME,cn=users,dc=office,dc=example,dc=pl` but CN in Active Directory holds `display name`. In openldap you can hold whatever you want in CN, but not in AD.

So having a user "Jan Dzban" gives me:
 - CN=Jan Dzban,CN=Users,DC=office,DC=example,DC=pl
 - displayName: Jan Dzban
 - sAMAccountName: jan.dzban
 - mail: jan.dzban@example.com

 `curl http://localhost:8000/api/v1/jobs -u "Jan Dzban":"password"` - this is how it works, but using display name here is not very common solution. I should be able to specify what field I want to use for authentication. Most common cases are `sAMAccountName` or `mail`. That is why ldap backends almost always let user to bind as some kind of system user, then retrieve specific field with an ldap filter, then match it with {USERNAME}.

**Comment by mlowicki** [comment]
@zolech can you share LDAP configuration used by your Vault servers?

**Comment by zolech** [comment]
Sure. Here it is:

![vault](https://user-images.githubusercontent.com/2222322/47033324-c701de00-d174-11e8-9207-c166f4d76da6.PNG)

That one works with our AD. Mind that there is no filter for searching users but it is probably harcoded to be something like `(&(objectClass=user)({userattribute}={username}))` - this is just my guess.

**Comment by mlowicki** [comment]
@zolech do you have `BindPassword` or `DiscoverDN` set? If so which one (or both)?

**Comment by zolech** [comment]
@mlowicki DiscoverDN - no, BindPassword - yes

**Comment by mlowicki** [comment]
@zolech on branch https://github.com/mlowicki/rhythm/tree/ldap_authorizer I've added support for user search - please set `binddn` and `bindpassword`. Rhythm will perform user search to get user binddn.

**Comment by mlowicki** [comment]
@zolech  do you authenticate now using what sits in `sAMAccountName` so sth like `jan.dzban` or still using `CN`?

**Comment by zolech** [comment]
I've forgot to write that. Yeah I am using `sAMAccountName` with `jan.dzban` as a user's login. Here is a configuration:

```
"auth": {
  "backend": "ldap",
        "ldap": {
           "addrs": ["ldap://dc1.example.pl"],
           "userdn": "cn=users,dc=office,dc=example,dc=pl",
           "userattr": "sAMAccountName",
	   "binddn": "cn=auth-user,cn=users,dc=office,dc=example,dc=pl",
 	   "bindpassword": "SomeExamplePasswd"
        }
}
```

**Comment by mlowicki** [comment]
Awesome. Thank you.

So  the next step is get groups from LDAP.

**Comment by mlowicki** [comment]
@zolech I've copied basic group search from Vault - https://github.com/mlowicki/rhythm/commit/a1477bdf54d9cf0e622b53d8feab1714bf18879e. For now it simply display debug message (so logging level has to be set to "debug") with found groups like:
```
DEBU[0271] LDAP groups: [infra]                          source="ldap/ldap.go:275"
```
You can test it out if it works fine in your scenario.

**Comment by zolech** [comment]
In vault I can use placeholder for `userdn` like this `(&(objectClass=group)(member:1.2.840.113556.1.4.1941:={{.UserDN}}))`. Can I do same here? It works when I type userdn staticaly, but it must be dynamicaly since it's different for every user.

**Comment by mlowicki** [comment]
Yes, you can - even default value for `groupfilter` uses it - `"(|(memberUid={{.Username}})(member={{.UserDN}})(uniqueMember={{.UserDN}}))"` (both `{{.UserDC}}` and `{{.Username}}` can be used).

**Comment by zolech** [comment]
Indeed. It works fine as it should. I must have been type this placeholder wrong before.

**Comment by mlowicki** [comment]
@zolech I've just pushed into branch change where first ACL from config file is checked. If it gives you read-write access then it's done. If read-only or no-access based on ACL from config then group search is triggered. If user is a member of matching group (exactly the same name) then read-write access is granted. Otherwise it fallbacks to access from ACL (so either read-only or no-access). Let me if it works and what to do you think about this behaviour.

**Comment by mlowicki** [comment]
The way it works currently is like this:
```
Client must authenticate using [Basic auth](https://en.wikipedia.org/wiki/Basic_access_authentication) passing username and password.
Under the hood backend first checks ACL from config file (`acl` config option for `LDAP` backend - [doc](https://github.com/mlowicki/rhythm#api-1)).
If ACL gives read-write access then such access is granted. Otherwise LDAP is queried for groups user is a member of.
If matching group is found then read-write access is granted, if not then it fallbacks to ACL (so either read-only or no access if not found). 

```

So currently `acl` in config is used when authenticated user is found there - then groups from LDAP aren't used at all. If user is not found in `acl` then if such user is a member of LDAP group which has the same name as job's group then read-write access is granted. Of course this is current behaviour from branch.

We can add some sort of mapping like if user is a member of LDAP group X then such user has e.g. read-only access to jobs under foo/bar and read-write to jobs under baz/*. Is this what you need?

**Comment by zolech** [comment]
>  if user is a member of LDAP group X then such user has e.g. read-only access to jobs under foo/bar and read-write to jobs under baz/*. Is this what you need?

Yes, that would be awesome. Having separate ACL's for every user (we have around 40) is hard to maintain. I would have to add/remove them in config file everytime someone get hired/fired. Group mapping helps here a lot since I just specify one ACL per ldap group and then just add/remove users directly in ldap.

**Comment by mlowicki** [comment]
Sounds reasonable @zolech. I've pushed changes into `ldap_authorizer` branch. Now it works as follows:

> Client must authenticate using [Basic auth](https://en.wikipedia.org/wiki/Basic_access_authentication) passing username and password. Under the hood backend first checks `useracl` from config file ([configuration doc](https://github.com/mlowicki/rhythm#api-1)). If `useracl` gives read-write or read-only access then such access is granted. Otherwise LDAP is queried for groups user is a member of. For each group `groupacl` from config file is checked to see what access level is granted for that group. Maximum access level across all user's group is granted.

**Comment by mlowicki** [comment]
@zolech I've changed format of jobs (like `LastFail` is now `LastFailedTask`) so please remove job through API and add it once again:
```
curl -X DELETE ADDR/api/v1/jobs/group/project/id
```

**Comment by mlowicki** [comment]
Added `caseSensitiveNames` option and merge onto master branch.
